name: Release Build & Deploy

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == false
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Zip static build
        run: zip -r out.zip out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: out.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build # 👈 ensures deploy waits for build
    if: github.event.release.prerelease == false
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build
          path: .

      - name: Unzip out.zip
        run: unzip -o out.zip -d ./out

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: main
          destination_repo: SamsterZero/SamsterZero.github.io
